### PR TITLE
Glizzy tokens

### PR DESCRIPTION
**Pull request by ErgoTester**

### CODE REVIEW

**Comment by arobsn** [comment]
Can you please provide more context on what Glizzy tokens are?

**Comment by ErgoTester** [comment]
GIF (the hotdog) is the new token by the greasycex team 
bun,ketchup and mustard are the token received for staking GIF via crooks finance

**Comment by ErgoTester** [comment]
https://app.spectrum.fi/ergo/liquidity/31ac0a34ae1aa473ddceabe1647449c9cfd84bab2e9d54dce0f2ff0abcd38c8a

**Comment by arobsn** [comment]
Ok, thanks

**Review by arobsn — APPROVED** [review]

**Pull request merged**
